apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: my-app
          image: nginx
          ports:
            - containerPort: 80
